#!/usr/bin/env python3
# Copyright (c) 1981-86 Robert A. Koeneke
# Copyright (c) 1987-94 James E. Wilson
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generates data/lang/pseudo/umoria.po, a pseudolocalization catalog
derived mechanically from data/lang/umoria.pot: every msgid becomes a
msgstr where each ASCII letter is replaced by its Unicode fullwidth
form (e.g. "Hello" -> "Ｈｅｌｌｏ").

Fullwidth text is deliberately worst-case-wide (each converted letter
occupies 2 terminal display columns instead of 1, like a Japanese
kana/kanji character does), so this exercises every display-width-vs-
byte-length assumption in the UI layout code in a single pass, without
needing real translation data.

printf format specifiers (%s, %d, %-5d, %.3d, %%, ...) are left
untouched as atomic tokens -- converting the conversion-character
letter (e.g. the "d" in "%d") would corrupt the format string. The &
and ~ item-description template markers, and the \\n \\t \\" \\\\
escape sequences, are never touched either: none of them are ASCII
letters, so the letter-only conversion rule already leaves them alone.

A msgctxt line (phase 10, e.g. `msgctxt "flavor"` on unidentified-item
flavor words) immediately preceding a msgid is carried through verbatim
into the generated pseudo catalog, so a msgctxt-qualified entry
pseudolocalizes and round-trips through src/lang.cpp's C_() lookup the
same way a context-free entry round-trips through _().

Usage: python3 scripts/make_pseudo_po.py
Writes data/lang/pseudo/umoria.po relative to the repository root
(this script's grandparent directory).
"""

import re
import sys
from pathlib import Path

MSGID_RE = re.compile(r'^msgid "((?:[^"\\]|\\.)*)"$')
MSGCTXT_RE = re.compile(r'^msgctxt "((?:[^"\\]|\\.)*)"$')

# Matches one printf conversion specifier as a single atomic token, e.g.
# %s  %d  %c  %-5d  %.3d  %6.2f  %02ld  %%
PRINTF_SPEC_RE = re.compile(
    r"%[-+0# ]*(?:\*|\d+)?(?:\.(?:\*|\d+))?[hlLqjzt]*[diouxXeEfFgGaAcspn%]"
)

# Matches one supported escape sequence as a single atomic token (the
# same subset src/lang.cpp's decodeEscapes() understands).
ESCAPE_RE = re.compile(r'\\[ntr"\\]')

PROTECTED_RE = re.compile(f"({PRINTF_SPEC_RE.pattern}|{ESCAPE_RE.pattern})")


def fullwidthLetter(ch):
    if "a" <= ch <= "z" or "A" <= ch <= "Z":
        return chr(ord(ch) + 0xFEE0)
    return ch


def pseudoTransform(msgid):
    out = []
    pos = 0
    for match in PROTECTED_RE.finditer(msgid):
        out.append("".join(fullwidthLetter(ch) for ch in msgid[pos:match.start()]))
        out.append(match.group(0))
        pos = match.end()
    out.append("".join(fullwidthLetter(ch) for ch in msgid[pos:]))
    return "".join(out)


def extractEntries(pot_path):
    """Returns a list of (context_or_None, msgid) tuples in file order.
    A msgctxt line is consumed by (and only applies to) the msgid line
    immediately following it, matching the .pot writer in
    extract_strings.py and the loadCatalog() parser in src/lang.cpp."""
    entries = []
    pending_context = None
    with pot_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")

            ctx_match = MSGCTXT_RE.match(line)
            if ctx_match:
                pending_context = ctx_match.group(1)
                continue

            msgid_match = MSGID_RE.match(line)
            if msgid_match:
                entries.append((pending_context, msgid_match.group(1)))
                pending_context = None
    return entries


def writePseudoPo(entries, out_path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("# Umoria pseudolocalization (pseudo) message catalog\n")
        f.write("#\n")
        f.write("# Generated by scripts/make_pseudo_po.py from data/lang/umoria.pot.\n")
        f.write("# Do not edit by hand; regenerate after umoria.pot changes.\n")
        f.write("#\n")
        f.write("# Every ASCII letter in each msgid is replaced with its Unicode\n")
        f.write('# fullwidth form, so this catalog surfaces display-width-vs-byte-\n')
        f.write("# length layout bugs (run with MORIA_LANG=pseudo) ahead of real\n")
        f.write("# translation work.\n")
        f.write("\n")
        for context, msgid in entries:
            if context is not None:
                f.write(f'msgctxt "{context}"\n')
            f.write(f'msgid "{msgid}"\n')
            f.write(f'msgstr "{pseudoTransform(msgid)}"\n')
            f.write("\n")


def main():
    repo_root = Path(__file__).resolve().parent.parent
    pot_path = repo_root / "data" / "lang" / "umoria.pot"
    out_path = repo_root / "data" / "lang" / "pseudo" / "umoria.po"

    if not pot_path.exists():
        print(f"error: {pot_path} not found", file=sys.stderr)
        return 1

    entries = extractEntries(pot_path)
    writePseudoPo(entries, out_path)
    print(f"wrote {len(entries)} entries to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
